### ISSUE TITLE
[EquipmentAndQuickSlots] Equipment lost on death by enemy damage

### ISSUE THREAD

**Issue by SSyl** [RandyKnapp/ValheimMods#69]
Hi,

I did some testing using *only* the Equipment and Quickslots plugin enabled and I figured out that you only lose your equipment if you die from damage by an enemy. If you die from fall damage, burning by standing on a campfire, etc., you don't lose your equipment.

Funny enough, while testing this, enemies that I manually spawned via the console **did not** cause me to lose my equipment. Only enemies that were naturally spawned by the game that killed me cause me to lose my equipment. I'm not sure if that was just a fluke, but I can confirm that every time I died from naturally spawned enemies I did lose my equipment.

It seems like the only equipment you actually lose is your Helmet, Chest, and Legs. In my testing it always let me keep my utility item and my cloak. That said, I didn't have a full inventory so it's possible that those get lost as well if you die from enemy damage with a full inventory.

Edit: Related to [this ](https://github.com/RandyKnapp/ValheimMods/issues/63)issue, but I made a separate one since this is only about equipment loss.

**Comment by RandyKnapp** [comment]
How strange, I will investigate

**Comment by SSyl** [comment]
Below is a link to a video of me testing it. I only included the part where I died from enemy damage and retrieved my corpse, but the full video shows me dying from fall damage beforehand and not losing any equipment. I can upload that if you need it.

https://gfycat.com/skinnyharmoniousilladopsis

Also, this testing was done when I was playing locally using my test/debug character, but I lost my actual character's equipment on my dedicated server which doesn't use cheats at all. So it happens regardless of host type. Also, the testing on this character was done using no mods except for Equipment and Quick Slots.

**Comment by RandyKnapp** [comment]
I think I have a fix for this, please update to latest and try it out.

**Comment by RandyKnapp** [comment]
I think this is fixed in 2.0.2

**Comment by thearn** [comment]
I'm on 2.0.4, but sadly still experiencing this. I'm not sure how to screen capture to document the issue.

**Comment by SSyl** [comment]
I haven't experienced the issue since updating. Are you using any other mods that interact with graves?
